#specs for travis ci
language: python
os: linux
matrix:
  include:
    - python : 3.6
    - python : 3.7
      dist: xenial
      sudo: true
# get the dependencies
install:
  - pip install .
# install what we need for testing
before_install:
  - pip install pytest pytest-cov codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# script for tests
script:
  - pytest --cov=./moseq2_pca
# after_success:
  - codecov -t e50ae5a9-5294-4e2b-87c6-070f8376a8b7
