#specs for travis ci
language: python
dist: trusty
os: linux
cache: false

stages:
  - latest-installs
  - name: latest-pythons
    if: branch = master

jobs:
  include:
    - env: ISOLATED=true
      python: '3.6'
      stage: latest-installs
      before_install:
        - pip install -U pip
        - pip install pipenv
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script:
        - make
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      dist: xenial
      python: '3.7'
      stage: latest-pythons
      before_install:
        - pip install pipenv
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script:
        - make
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      python: '3.6'
      stage: latest-installs
      before_install:
        - pip install -U pip
        - pip install awscli
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pip install -e .
      before_script:
        - make
      script:
        - pytest --cov=./moseq2_pca/tests/
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID

    - env: ISOLATED=true
      dist: xenial
      python: '3.7'
      stage: latest-pythons
      before_install:
        - pip install -U pip
        - pip install awscli
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
      install:
        - pip install -e .
      before_script:
        - make
      script:
        - pytest --cov=./moseq2_pca/tests/
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID