#specs for travis ci
language: python
os: linux
python:
  - 3.6
# - 3.7 enable once supported by travis
# get the dependencies
install:
  - pip install .
# install what we need for testing
before_install:
  - pip install -U pip
  - pip install awscli
  - pip install pytest codecov
  - pip install "pytest-cov>=2.4.0,<2.6"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_script: make
# script for tests
script:
  - pytest --cov=./moseq2_pca
# after_success:
  - codecov -t e50ae5a9-5294-4e2b-87c6-070f8376a8b7
