#specs for travis ci
language: python
os: linux
python:
  - 3.6
# - 3.7 enable once supported by travis
# get the dependencies

# install what we need for testing
before_install:
  - pip install pipenv
  - pip install pytest codecov
  - pip install "pytest-cov>=2.4.0,<2.6"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pipenv install --dev --ignore-pipfile --deploy
before_script:
  - make
script:
  - pipenv run pytest --cov-report xml --cov-report term
after_success:
  - codecov -t e50ae5a9-5294-4e2b-87c6-070f8376a8b7 # hide this
